export { default as Logo } from './EchoSign.png'
export { default as recording } from './undraw_recording_re_5xyq.svg'
export { default as selfie } from './undraw_selfie_re_h9um.svg'
export { default as video } from './undraw_video_files_fu10.svg'
export { default as registeration } from './undraw_access_account_re_8spm.svg'
export { default as contact } from './undraw_personal_email_re_4lx7.svg'

export { default as About1 } from './about_1.svg'
export { default as About2 } from './about_2.png'
export { default as About3 } from './about_3.svg'
export { default as Contact } from './contact.svg'
export { default as empty } from './empty.png'