export { default as Register } from './Auth/Register'
export { default as Login } from './Auth/Login'
export { default as ForgetPassword } from './Auth/ForgetPassword'
export { default as ResetPassword } from './Auth/ResetPassword'
export { default as TermsAndConditions } from './Auth/TermsAndConditions'
export { default as ChangePassword } from './Auth/ChangePassword'
export { default as VerifyEmail } from './Auth/VerifyEmail'
export { default as Contact } from './Auth/Contact'

export { default as LandingPage } from './LandingPage'
export { default as Dashboard } from './Dashboard'
export { default as Profile } from './Profile'
export { default as About } from './About'
export { default as Users } from './Users'
export { default as TextToVoice } from './TexttoVoice'