export { default as Register } from './Auth/Register'
export { default as Login } from './Auth/Login'
export { default as ForgetPassword } from './Auth/ForgetPassword'
export { default as ResetPassword } from './Auth/ResetPassword'
export { default as TermsAndConditions } from './Auth/TermsAndConditions'
export { default as ChangePassword } from './Auth/ChangePassword'
export { default as VerifyEmail } from './Auth/VerifyEmail'
export { default as Contact } from './Auth/Contact'

export { default as Home } from './Dashboard/Home'